kborodulin/budget

- .gitignore
- pom.xml
- src/main/resources/log4j2.properties
- src/main/webapp/WEB-INF/dispatcher-servlet.xml
- src/main/webapp/WEB-INF/logging.properties
- src/main/webapp/WEB-INF/web.xml
Project structure was made.
Configuration and property files was added.
> FBCF-007: Base configuration of web-service was implemented.

- src/main/java/ru/innopolis/controller/RegController.java
- src/main/java/ru/innopolis/db/model/User.java
- src/main/java/ru/innopolis/service/RegService.java
- src/main/java/ru/innopolis/service/RegServiceImpl.java
- src/main/java/ru/innopolis/service/dto/UserDto.java
- src/main/webapp/WEB-INF/views/personalAccount.jsp
- src/main/webapp/WEB-INF/views/registration.jsp
Service, dto and db-model files was created as mock.
> FBCF-013: Controller for registration was added.

- pom.xml
- src/main/java/ru/innopolis/db/dao/UserDao.java
- src/main/java/ru/innopolis/db/dao/UserDaoImpl.java
- src/main/java/ru/innopolis/db/model/User.java
- src/main/java/ru/innopolis/service/RegService.java
- src/main/java/ru/innopolis/service/RegServiceImpl.java
- src/main/java/ru/innopolis/service/dto/UserDto.java
DAO classes was added as mock.
> FBCF-014: Service for registration was added.

- .gitignore
- src/main/java/ru/innopolis/db/dao/ConnectionDB.java
Folder log was added in .gitignore.
> FBC-002: Fix ConnectionDB: drivers loading and logging were added.

- pom.xml
- src/main/java/ru/innopolis/controller/LoginController.java
- src/main/java/ru/innopolis/controller/RegController.java
- src/main/webapp/WEB-INF/spring/application-security.xml
- src/main/webapp/WEB-INF/spring/dispatcher-servlet.xml
- src/main/webapp/WEB-INF/spring/root-context.xml
- src/main/webapp/WEB-INF/views/login.jsp
- src/main/webapp/WEB-INF/web.xml
Controller for login view was added.
> FBCF-026: Spring security module was added.

- src/main/java/ru/innopolis/controller/AccountController.java
- src/main/java/ru/innopolis/security/SaveUserInSessionHandler.java
- src/main/webapp/WEB-INF/spring/application-security.xml
Authentication success handler was added.
AccountController was corrected to use info about user from session.
> FBCF-101: Save user in session function was added.

- src/main/java/ru/innopolis/controller/AlertProcController.java
- src/main/webapp/WEB-INF/views/include/navBar.jsp
- src/main/webapp/resources/js/personalAccount.js
Controller was added and view was corrected.
> FBCF-032: Alert processing was added.

- src/main/java/ru/innopolis/controller/ExpensesController.java
- src/main/java/ru/innopolis/controller/ReferenceController.java
- src/main/java/ru/innopolis/service/OperationService.java
- src/main/java/ru/innopolis/service/impl/OperationServiceImpl.java
Изменил контроллер справочников ReferenceController
> FBCF-240. добавил контроллер расходов ExpensesController

- src/main/java/ru/innopolis/controller/ReferenceController.java
- src/main/resources/liquibase/changelog/db.changelog-0.1.0.xml
- src/main/webapp/WEB-INF/views/income.jsp
- src/main/webapp/WEB-INF/views/ref/allcategory.jsp
- src/main/webapp/resources/js/refCategory.js
- src/main/webapp/resources/js/utils.js
- сумма ограничил длину до 9 символов
- справочник категорий подгружается из бд
- комментарий увеличил поле и ограничил до 50 символов
- добавил поле с датой операции
> FBCF-243. вкладка "доход"

- src/main/java/ru/innopolis/controller/AccountController.java
- src/main/java/ru/innopolis/controller/AlertProcController.java
- src/main/java/ru/innopolis/controller/LeftFamilyController.java
- src/main/java/ru/innopolis/controller/RegController.java
- src/main/java/ru/innopolis/domain/Account.java
- src/main/java/ru/innopolis/domain/Alert.java
- src/main/java/ru/innopolis/domain/Famem.java
- src/main/java/ru/innopolis/domain/Family.java
- src/main/java/ru/innopolis/domain/Role.java
- src/main/java/ru/innopolis/domain/User.java
- src/main/java/ru/innopolis/repository/AlertRepository.java
- src/main/java/ru/innopolis/repository/FamemRepository.java
- src/main/java/ru/innopolis/service/AlertService.java
- src/main/java/ru/innopolis/service/FamemService.java
- src/main/java/ru/innopolis/service/FamilyService.java
- src/main/java/ru/innopolis/service/UserService.java
- src/main/java/ru/innopolis/service/impl/AlertImpl.java
- src/main/java/ru/innopolis/service/impl/FamemServiceImpl.java
- src/main/java/ru/innopolis/service/impl/FamilyServiceImpl.java
- src/main/java/ru/innopolis/service/impl/UserServiceImpl.java
- src/main/resources/liquibase/changelog/db.changelog-0.1.0.xml
- src/main/webapp/WEB-INF/views/account.jsp
- src/main/webapp/WEB-INF/views/include/familyExist.jsp
Relations was added for some entities.
Services were refactored due to domain changes. 
AccountController, AlertProcController and LeftFamilyController were refactored due to domain changes.
All unnecessary code was deleted.
> FBCF-114: Domain was refactored. 

- src/main/java/ru/innopolis/controller/AccountController.java
- src/main/java/ru/innopolis/controller/LeftFamilyController.java
- src/main/java/ru/innopolis/domain/Famem.java
- src/main/java/ru/innopolis/repository/AlertRepository.java
- src/main/java/ru/innopolis/service/AlertService.java
- src/main/java/ru/innopolis/service/impl/AlertImpl.java
- src/main/java/ru/innopolis/service/validators/EmailForAlertReceiverValidator.java
System get all alerts for receiver, find first unprocessable alert and displays it.
Famem entity was corrected to stores alerts.
In EmailForAlertReceiverValidator new validations were added.
> FBCF-109: Logic for alert display was corrected.

- src/main/java/ru/innopolis/controller/AccountController.java
Initiator(user) is get from service to refresh all fields.
> FBCF-005: Fix error which occurs during inviting member.

- src/main/java/ru/innopolis/controller/ExpensesController.java
- src/main/java/ru/innopolis/controller/IncomeController.java
- src/main/java/ru/innopolis/controller/TestController.java
- src/main/java/ru/innopolis/domain/Operation.java
- src/main/java/ru/innopolis/repository/OperationRepository.java
- src/main/java/ru/innopolis/service/OperationService.java
- src/main/java/ru/innopolis/service/impl/OperationServiceImpl.java
- src/main/webapp/WEB-INF/views/expenses.jsp
- src/main/webapp/resources/js/expenses.js
-подтягиваются справочники счетов и категорий
-ограничены поля ввода
-отображаются расходы за день
-возможность добавления расходов
-возможность удаления расходов
> FBCF-115: Реализованы некоторые возможности вкладки Расходы:

- src/main/java/ru/innopolis/controller/ExpensesController.java
- src/main/java/ru/innopolis/enums/Periods.java
- src/main/java/ru/innopolis/service/DateAnalizer.java
- src/main/java/ru/innopolis/service/impl/DateAnalizerImpl.java
На вход - наименование периода (или строка на английском, или enum), на выходе - начальная и конечная даты.
> FBCF-117: Добавлен сервис по парсингу периода.

- src/main/java/ru/innopolis/controller/MainController.java
- src/main/java/ru/innopolis/controller/TestController.java
- src/main/java/ru/innopolis/domain/Account.java
- src/main/java/ru/innopolis/repository/AccountRepository.java
- src/main/java/ru/innopolis/repository/OperationRepository.java
- src/main/java/ru/innopolis/service/AccountService.java
- src/main/java/ru/innopolis/service/OperationService.java
- src/main/java/ru/innopolis/service/impl/AccountServiceImpl.java
- src/main/java/ru/innopolis/service/impl/OperationServiceImpl.java
- src/main/webapp/WEB-INF/views/charts/categoryExpensesChart.jsp
- src/main/webapp/WEB-INF/views/charts/memberBalanceChart.jsp
- src/main/webapp/WEB-INF/views/charts/memberExpensesChart.jsp
- src/main/webapp/WEB-INF/views/include/progress.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/resources/js/chartsLoad.js
- src/main/webapp/resources/js/utilsChart.js
> FBCF-118: Разработано отображение главной страницы (бэк и фронт). 

- src/main/java/ru/innopolis/controller/IncomeController.java
- src/main/java/ru/innopolis/controller/MainController.java
- src/main/java/ru/innopolis/repository/AccountRepository.java
- src/main/java/ru/innopolis/repository/OperationRepository.java
- src/main/java/ru/innopolis/security/SaveUserInSessionHandler.java
- src/main/java/ru/innopolis/service/OperationService.java
- src/main/java/ru/innopolis/service/impl/AccountServiceImpl.java
- src/main/java/ru/innopolis/service/impl/OperationServiceImpl.java
- src/main/webapp/WEB-INF/spring/application-security.xml
- src/main/webapp/WEB-INF/views/include/progress.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/resources/js/chartsLoad.js
- балансы семьи отображаются списком
- чартов два. только по расходам. Отображаются только, если есть расходы.
- добавлена информация о последний операциях в семье. Отобраается только, если есть операции.
- добавлено отдельное отбражение главной страницы при отсутствии семьи.
- редирект на главную после логина
> FBCF-121: Изменения отображения главной страницы:

- src/main/java/ru/innopolis/controller/AccountController.java
- src/main/webapp/WEB-INF/views/include/familyExist.jsp
- src/main/webapp/resources/js/personalAccount.js
Добавлена возможность изменить название семьи.
Имя семьи - не уникальное поле.
> FBCF-122: Проверка на наличие семьи с таким же именем убрана.

- src/main/java/ru/innopolis/controller/TransactionController.java
- src/main/java/ru/innopolis/controller/WalletController.java
- src/main/java/ru/innopolis/domain/Transaction.java
- src/main/java/ru/innopolis/repository/AccountRepository.java
- src/main/java/ru/innopolis/service/AccountService.java
- src/main/java/ru/innopolis/service/OperationService.java
- src/main/java/ru/innopolis/service/impl/AccountServiceImpl.java
- src/main/java/ru/innopolis/service/impl/OperationServiceImpl.java
- src/main/webapp/WEB-INF/views/include/mainMenu.jsp
- src/main/webapp/WEB-INF/views/include/modalCreateAccount.jsp
- src/main/webapp/WEB-INF/views/include/modalEditAccount.jsp
- src/main/webapp/WEB-INF/views/include/walletPeriodSelection.jsp
- src/main/webapp/WEB-INF/views/transactions.jsp
- src/main/webapp/WEB-INF/views/wallet.jsp
- src/main/webapp/resources/js/fillAccounts.js
- src/main/webapp/resources/js/fillWallets.js
- src/main/webapp/resources/js/wallets.js
Разделил страницы счета и переводы. 
Добавил историю.
> FBCF-306: Transaction operation history

- src/main/java/ru/innopolis/controller/AccountController.java
- src/main/java/ru/innopolis/interceptor/AlertInterceptor.java
- src/main/webapp/WEB-INF/spring/dispatcher-servlet.xml
- src/main/webapp/WEB-INF/views/expenses.jsp
- src/main/webapp/WEB-INF/views/include/familyExist.jsp
- src/main/webapp/WEB-INF/views/statistic.jsp
Обработка также на всех страницах, но после обработки отпарвляет на страницу Личные данные.
Плюс изменила отображениие инфо о пользователях в разделах "Приглашения" и "Члены семьи".
>  FBCF-125: Алерт-приглашение в семью отображается на всех страницах.

- src/main/java/ru/innopolis/service/impl/CheckpointsGeneratorImpl.java
- src/main/webapp/WEB-INF/views/expenses.jsp
- src/main/webapp/WEB-INF/views/income.jsp
- src/main/webapp/WEB-INF/views/main.jsp
Добавлен комментарий для операций на главной странице.
Скорректированы названия столбцов в расходах и доходах.
>  FBCF-130: Шаг для для чекпоинтов статистики уменьшен +
